dist: xenial
language: python

env:
  - $PYTEST_VERSION=3.6.0  # min version
  - $PYTEST_VERSION=4.6.9
  - $PYTEST_VERSION=5.3.5
  - $PYTEST_VERSION=5.4.1  # last version
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install m2r==0.2.1
  - pip install pytest==$PYTEST_VERSION
  - python setup.py install
script:
  - pytest
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
    python: "3.8"