language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --system
  - python setup.py install
# command to run tests
script:
  - pytest ./test