dist: xenial
language: python

env:
  global:
    - LAST_PYTEST_VERSION=5.4.1
  jobs:
    - PYTEST_VERSION=3.6.0  # min support version
    - PYTEST_VERSION=4.6.9
    - PYTEST_VERSION=5.3.5
    - PYTEST_VERSION=$LAST_PYTEST_VERSION

git:
  depth: false

python:
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pytest==$PYTEST_VERSION
  - pip install pytest-cov==2.8.1
  - pip install -e .
script:
  - pytest ./tests
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_existing: true
  distributions: bdist_wheel --universal
  on:
    tags: true
    repo: tolstislon/pytest-bug
    python: "3.8"
    condition: $PYTEST_VERSION == $LAST_PYTEST_VERSION

after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    on_success: never
    on_failure: always