dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
virtualenv:
  system_site_packages: true
install:
  - pip install m2r
  - pip install pytest==$PYTEST_VERSION
script:
  - pytest ./test