dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install m2r
  - pip install pytest==$PYTEST_VERSION
  - python setup.py install
script:
  - pytest ./test